POST http://localhost:8081/user/signup
Content-Type: application/json 

{
    "email": "cdon@gmail.com",
    "password": "Tochi12345!",
    "birthdate": "2004-06-21"
}

###

POST http://localhost:8081/user/login
Content-Type: application/json 

{
    "email" : "lindseymcgovern04@gmail.com",
    "password" : "Sharon122!"
}

###
GET http://localhost:8081/user/getAll
Content-Type: application/json

###

POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf2",
    "username" : "Tochi Edit",
    "password" : "dwwrwr"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf1"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "634edb2a16710b2cda6fb370"
}

###
POST  http://localhost:8081/post/deleteAll

###
GET http://localhost:8081/posts
Content-Type: application/json

###
POST  http://localhost:8081/post/createPost
Content-Type: application/json

{
    "content" : "test content",
    "userId" : "635ab8dfc407faf9f73deaf1",
    "username" : "Hi"
}