##api integration
@baseUrl = http://localhost:3000/api/trainlines

POST http://localhost:8081/user/signup
Content-Type: application/json 

{
    "email": "spraggins0602@gmail.com",
    "password": "F0rtun3c00k!3",
    "birthdate": "2004-06-02"
}

### log in
POST http://localhost:8081/user/login
Content-Type: application/json 

{
    "email" : "lindseymcgovern04@gmail.com",
    "password" : "Sharon122!"
}

### Make User an Admin
POST http://localhost:8081/user/makeUserAnAdmin
Content-Type: application/json

{
  "email": "",
  "password": "",
  "accessCode": "BlueLineIsTheBestLine12345"
}

###
GET http://localhost:8081/user/getAll
access-code: BlueLineIsTheBestLine12345
Content-Type: application/json

###
POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf2",
    "username" : "Userf8u2sf",
    "password" : "Tochi12345!"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : ""
}

###
DELETE http://localhost:8081/user/deleteUserByEmail
Content-Type: application/json

{
  "email": "",
  "accessCode": "BlueLineIsTheBestLine12345"
}

### Create a post
POST http://localhost:8081/posts/createPost
Content-Type: application/json

{
    "content" : "GO SOX!",
    "userId" : "67e9b2cf929242eb614074af",
    "username" : "User5g9fdw"
    "trainLineId": "Red"   // Optional: remove or change this to attach to a line
}

### Get all posts
GET http://localhost:8081/posts/
Content-Type: application/json

### Get posts made by a specific user by user ID
GET http://localhost:8081/posts/user/67e9b2cf929242eb614074af
Content-Type: application/json

### Get post by post ID
GET http://localhost:8081/posts/67ef0408f7531863f6aa0004
Content-Type: application/json

### Update post by post ID
PUT http://localhost:8081/posts/updatePost/67ef2c0dbc19694284ff1f32
Content-Type: application/json

{
    "content": "updated sox",
    "isSensitive": true,
    "hasOffensiveText": false
}

### Get Posts for Red Line
GET http://localhost:3000/posts/trainline/Red


### Delete a specific post by post ID
DELETE http://localhost:8081/posts/deletePost/67ef024deeaef67043af55bf
Content-Type: application/json

### Delete ALL posts
DELETE http://localhost:8081/posts/deleteAllPosts
Content-Type: application/json

### Create a comment
POST http://localhost:8081/comments/createComment
Content-Type: application/json

{
    "postID": "67f0151cd0bab9f6e3b892af",
    "userID": "67e9b2cf929242eb614074af",
    "username": "User5g9fdw",
    "content": "fenwayyyyy :)",
    "parentComment": null
}

### Get all comments
GET http://localhost:8081/comments
Content-Type: application/json

### Get comments by post ID
GET http://localhost:8081/comments/post/67f0151cd0bab9f6e3b892af
Content-Type: application/json

### Get a specific comment by comment ID
GET http://localhost:8081/comments/67edb6d932b701692faa3ca9
Content-Type: application/json


### Update comment by comment ID
PUT http://localhost:8081/comments/updateComment/67ef2c2fbc19694284ff1f38
Content-Type: application/json

{
    "content": "Updated fenway!"
}

### Delete a specific comment by comment ID
DELETE http://localhost:8081/comments/deleteComment/67eeffca6e54f867372a82d1
Content-Type: application/json

### Delete ALL comments
DELETE http://localhost:8081/comments/deleteAllComments

### Add a like
POST http://localhost:8081/likes/
Content-Type: application/json

{
  "userID": "67e9b2cf929242eb614074af",
  "postID": "67ed66004c5bc5fd51ee59a1"
}

### Remove a like
DELETE http://localhost:8081/likes/67ed66004c5bc5fd51ee59a1/67e9b2cf929242eb614074af/
Content-Type: application/json

### Get like count
GET http://localhost:8081/likes/users/67ed66004c5bc5fd51ee59a1/
Content-Type: application/json

### Get users who liked a post
GET http://localhost:8081/likes/users/67ed66004c5bc5fd51ee59a1
Content-Type: application/json

### Check if user liked a post
GET http://localhost:8081/likes/67ed66004c5bc5fd51ee59a1/67e9b2cf929242eb614074af
Content-Type: application/json


### Follow/Unfollow trainline/user

### Follow a User
POST http://localhost:8081/follow/user/USER_ID
Authorization: Bearer YOUR_ACCESS_TOKEN
Content-Type: application/json

### Unfollow a User
POST http://localhost:8081/unfollow/user/USER_ID
Authorization: Bearer YOUR_ACCESS_TOKEN
Content-Type: application/json

### Follow Red Line
POST http://localhost:8081/following/line/Red
Content-Type: application/json

{
  "userId": "67e9b2cf929242eb614074af"
}

### Unfollow Red Line
POST http://localhost:8081/unfollow/line/Red
Content-Type: application/json

{
  "userId": "YOUR_USER_ID_HERE"
}

### Get Following Users & Train Lines
GET http://localhost:8081/following
Authorization: Bearer YOUR_ACCESS_TOKEN
Content-Type: application/json